### ISSUE TITLE
Doesn't work with images using data URIs

### ISSUE THREAD

**Issue by d3vr** [d3vr/viewimage#1]
- Images using data URIs are using a different class (`.irc_mut`). If no `.irc_mi` found check for the others. 
- `window.open()` wouldn't open data URIs: [potential fix](https://github.com/niklasvh/html2canvas/issues/1271)

**Comment by XanderLuciano** [comment]
Just sent a PR that should handle the `.irc_mut` cases :)

https://github.com/d3vr/viewimage/pull/2

**Comment by d3vr** [comment]
@XanderLuciano thanks for your help, I found a better approach that works for all cases. Check 7de20de51083810087ccc357c6e955ccc3198c14
