### ISSUE TITLE
Does not work on Firefox Quantum 59.0.3 (64-bit) Win8

### ISSUE THREAD

**Issue by prasunkgupta** [d3vr/viewimage#6]
Steps:
1. Open https://images.google.com/
2. Search for "big buck bunny"
3. Click on any image
4. Click on bookmarklet
5. Nothing happens!

**Comment by prasunkgupta** [comment]
Same behavior is reproduced on Google Chrome Version 66.0.3359 (official build) (64 bit)

**Comment by d3vr** [comment]
Should be fixed in 5c994c7836350305e903ac960d1276bbd2ff27fa, can you update your bookmarklets and try again please?

**Comment by prasunkgupta** [comment]
It works!
