### ISSUE TITLE
Does not work on Firefox Quantum 68.0.2 (64-bit) Win10

### ISSUE THREAD

**Issue by prasunkgupta** [d3vr/viewimage#7]
Steps:

-     Open https://images.google.com/
-     Search for "big buck bunny"
-     Click on any image
-     Click on bookmarklet
-     Nothing happens!

Same behavior is reproduced on Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Comment by d3vr** [comment]
Thanks for reporting. The issue has been fixed in the latest commit, please update your bookmarklets.

**Comment by prasunkgupta** [comment]
It does not work on my system.
Does a "search by image" when I click on the **new** View Image bookmarklet.

**Comment by d3vr** [comment]
My bad, fixed. Please update again and let me know if it's working for you now.

**Comment by prasunkgupta** [comment]
It works! Thank you for your efforts.
